### ISSUE TITLE
conda forge build of simplecrop

### ISSUE THREAD

**Issue by cpritcha** [openmodelingfoundation/meillionen#15]

**Comment by cpritcha** [comment]
@mcflugen do have any conda feedstock suggestions for simplecrop (the Fortran part and python parts)

**Comment by mcflugen** [comment]
@cpritcha I've opened a pull request for *simplecrop* on *conda-forge* (conda-forge/staged-recipes#14456). Right now it's just building and installing the *simplecrop* executable. I'm not sure of everything you want to include with the package but I thought this would be a good start. Anyway, please have a look and let me know what you think.

**Comment by cpritcha** [comment]
Thanks! That looks good to me. If I put the wheels for SimpleCrop wrapper on conda-forge and the python meillionen wrapper on pypi and conda-forge then that should make everything a easier to started with.

**Comment by cpritcha** [comment]
created at [simplecrop-feedstock](https://github.com/conda-forge/simplecrop-feedstock)
